### PR TITLE
Issue 322

### PR DESCRIPTION
**Pull request by James-N-M**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have added tests that prove your fix is effective or that your feature works.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Please describe your pull request.
Added a api endpoint for creating events
💔Thank you!

### CODE REVIEW

**Comment by Hasnayeen** [comment]
@James-N-M looks like github is having a problem https://status.github.com/messages

**Comment by Hasnayeen** [comment]
@James-N-M looks like github is having a problem https://status.github.com/messages

**Comment by Hasnayeen** [comment]
@James-N-M github having some issues https://status.github.com/messages

**Comment by James-N-M** [comment]
@Hasnayeen what could the conflict on change log be though ???

**Comment by James-N-M** [comment]
@Hasnayeen the issues with github really messed me up last night, I'm honestly going to fork again and submit a new pr for this issue, after i copy paste all of this changed code in my new fork branch 👍

**Comment by James-N-M** [comment]
closing to open a new one

**Pull request closed without merging**
