### PR TITLE
add status option to task

### PR DESCRIPTION
**Pull request by nbrabant**
create migration and statuses creation logic
add status_id to task

### CODE REVIEW

**Comment by Hasnayeen** [comment]
@nbrabant thanks for considering to contribute.
Two things I want to mention 1. every pr should have test for corresponding code, 2. pr should be opened against `master` branch. Check [Contribution Guideline](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) for more info.

**Comment by nbrabant** [comment]
Erf, i have missed this details, sorry
Is there a way to revoke the PR i do in master, i go to unit test before i PR in dev this time ;)

**Comment by Hasnayeen** [comment]
you don't have to revoke, just change the branch in pr , click edit then you can change the branch from dropdown

**Comment by Hasnayeen** [comment]
Resolves #194

**Pull request merged**
