### PR TITLE
added italian translation

### PR DESCRIPTION
**Pull request by alsd4git**
fixed issue #232 adding Italian translation

### CODE REVIEW

**Comment by Hasnayeen** [comment]
@alsd4git good work man, bellissimo. Can you add an entry in `config/locale.php` under `lang` key for italian translation. Grazie

**Comment by alsd4git** [comment]
@Hasnayeen   yes i can! sorry, i'll update asap

**Comment by Hasnayeen** [comment]
@alsd4git hey no need to be sorry, thanks for your contribution

**Comment by alsd4git** [comment]
i have added the line to my branch =)

**Pull request merged**
