### PR TITLE
Issue #1148 - Updated URL from goodworkfor.life to usegood.work

### PR DESCRIPTION
**Pull request by chrisvasey**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [X] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [X] Check you have included issue number in your pr (e.g #23).
- [N/A] Check you have added tests that prove your fix is effective or that your feature works.
- [N/A] Check your code additions will fail neither code linting checks nor unit test.
- [N/A] Check you added any notable changes to the `CHANGELOG.md` file.

*N.B* Only push atomic PR meaning single feature/update/fix in a PR. Don't combine multiple feature/update/fix in a single PR.

### Description
Please describe your pull request.

Updated project URL in readme following domain change.
Ref to issue #1148

💔Thank you!

### CODE REVIEW

**Comment by ffranchina** [comment]
Hello! 
By checking https://usegood.work, it doesn't look to me that #1148 is resolved since in the [demo page](https://usegood.work/demo) it still links the broken domain. Am I wrong?

**Comment by Hasnayeen** [comment]
demo is available at new domain `htttps://demo.goodwork.cloud`, thanks for the PR though.

**Comment by ffranchina** [comment]
@Hasnayeen The demo is still not functional:
image
Can you please have a look at it when you have time?
Thanks for your work! :)

**Comment by Hasnayeen** [comment]
@ffranchina fixed, thanks for notifying

**Comment by ffranchina** [comment]
@Hasnayeen no problem, thanks to you!
The 404 errors are gone but it's still not possible to interact with the platform, is that the intended behavior?

**Comment by Hasnayeen** [comment]
@ffranchina redesigning the whole app, so most of the things are just placeholder for now

**Pull request closed without merging**
