### PR TITLE
Loading modal for creating task, error notification if "duo on" not selected

### PR DESCRIPTION
**Pull request by Rafatlne**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [ ] Check you have added tests that prove your fix is effective or that your feature works.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Improvement: added loading modal when `create` task button pressed
BugFix: if `Due On` is not selected, it will show error notification

💔Thank you!

### CODE REVIEW

**Comment by Rafatlne** [comment]
You already merged this branch? I didn't notiched. I am going to delete this branch now

**Comment by Hasnayeen** [comment]
@Rafatlne no didn't merged into dev, merged dev branch commit into this pr, remove the loading related code and keep only due on bug related code

**Comment by Rafatlne** [comment]
I have now Conflicting files in `public/js/` folder, which i can't able to manually merge now.

**Comment by Hasnayeen** [comment]
@Rafatlne  ok looks like this got messy, you know what create a new pr for this (only the due on bug). I'm closing this

**Pull request closed without merging**
