### PR TITLE
Add standardjs GitHub action

### LINKED ISSUE #713: Add github action to run js lint to autofix code style issues
This project use [standardJS](https://standardjs.com/) for js code style. This action should run on any pull request created against dev branch to check js lint and auto fix them.

### PR DESCRIPTION
**Pull request by jopereyral**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [x] Check you have added tests that prove your fix is effective or that your feature works.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Add [standardJS](https://standardjs.com/) action to perform auto-commit  in any created pull request.

closes #713 

💔Thank you!

### CODE REVIEW

**Comment by Hasnayeen** [comment]
name of the secrets should be `ACCESS_TOKEN`

**Comment by jopereyral** [comment]
@Hasnayeen  Hi, actually Github creates the `GITHUB_TOKEN` secret automatically for every workflow

**Comment by Hasnayeen** [comment]
@jopereyral so I don't need to add any token in this repo settings for this to work?

**Comment by jopereyral** [comment]
@Hasnayeen  yes, [here's](https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret) more info about that secret

**Comment by Hasnayeen** [comment]
another thing, this action should apply only for pr open against dev branch, cause there is another branch where dependency pr is opened which doesn't need this action

**Comment by jopereyral** [comment]
That's a good point, let me update the .yaml file

**Pull request merged**
