### PR TITLE
Add Github API issues request

### PR DESCRIPTION
**Pull request by hulkur**
Resolves: #699 

### Description

Adds Github API request for issues. Refactored GithubTrait to be easier to extend with additional requests..
Also added minimal Issues tab on project page as it is not clear how or where issues list should eventually go. Good for a starting point and to show that it works.

### CODE REVIEW

**Comment by Hasnayeen** [comment]
@hulkur  Hey thanks for considering to contribute to the project. There are two issues with the pr -
1. Test is compulsory for the pr to be accepted
2. This issue is only to add an api in backend, frontend code is not necessary and according to the need, so frontend vue code should be removed

**Comment by hulkur** [comment]
Test needs to hit Github API and can only assert that there is some data returned but nothing on the content of that data.

**Comment by hulkur** [comment]
Made both actual and fake connector.
This way both actual github connection and data handling without actually hitting github can be tested.

**Comment by Hasnayeen** [comment]
you don't test the actual api in testing you just replace it with a mock service, no http request shoud be made during testing, also don't use any secret/key/token in the testing so all env method use should be removed and finally add a route for the api [`github-repo/{id}/issues`] and change the test to http test instead of class test

**Comment by hulkur** [comment]
In automatic test you don't test actual api, but you want to have the possibility in manual integration  test and then you need to have some kind of safe way to provide access token and repo id. `env()` using `.env.testing` is one of those ways.
Mock service is also there - `FakeGithubConnection` - and this is used in automatic testing.

http/browser test is frontend test and you wanted all frontend stuff removed. Additionally you should not directly call github api requests. Separation layer is good to have in case for example github output changes.

**Comment by Hasnayeen** [comment]
we don't have any manual integration test and don't intend to have it in near future so that's not necessary, you can remove that. and not frontend test but http api test, testing our api that when called its work and return proper response. you can check other api tests in the test suite for example.

**Comment by hulkur** [comment]
That is not a good thing. You need to have integration tests to make sure your code will actually work in production. No amount of mocking will help you with that.

I see that in your design frontend has github repo id, but as repos are connected to entities then all github request should go through these entities. To have less replication in code, entities should have `hasGithub` trait which makes calls to github connection and returns data in unified way.
This way actual api call is `/project/{id}/issues` in which additional validations can be made ex. does the entity actually have a connected repo.

**Pull request closed without merging**
