### PR TITLE
Fix error in docker build #733

### PR DESCRIPTION
**Pull request by BBBThunda**
Replace now-obsolete mysql-client package with mariadb-client per Ubuntu

### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [x] Check you have added tests that prove your fix is effective or that your feature works.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
See https://github.com/iluminar/goodwork/issues/733
Running `install.sh` was failing during docker build because we were trying to install an aptitude package `mysql-client` that no longer exists in the package repository. Ubuntu replaced it with `mariadb-client`.

Update the Dockerfile to include `mariadb-client` instead of an package that is no longer valid.

### CODE REVIEW

**Comment by Hasnayeen** [comment]
pr should follow the pr checklist

**Comment by BBBThunda** [comment]
Ah I think I misread the part about comparing against the dev branch - I'll create a new PR.

Is that the only thing I was missing?

**Comment by Hasnayeen** [comment]
yes, you can change the base branch by clicking edit at top

**Comment by BBBThunda** [comment]
Is there something I need to do to trigger the `php-cs-fixer` pipeline?

**Pull request merged**
