### PR TITLE
Fix validation rules for task creation

### PR DESCRIPTION
**Pull request by djaca**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [ ] Check you have included issue number in your pr (e.g #23).
- [ ] Check you have added tests that prove your fix is effective or that your feature works.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Please describe your pull request.

💔Thank you!

### CODE REVIEW

**Comment by Hasnayeen** [comment]
@djaca  the previous validation rules are correct and what is intended so closing this pr.

**Comment by djaca** [comment]
Try to create task without assigned_to... Task is created, but can not open created task...

**Comment by Hasnayeen** [comment]
Then the bug is on frontend, it needs to be fixed there

**Comment by djaca** [comment]
assigned_to field is current nullable, but must me required because in repository you have `'assigned_to'       => $data['assigned_to'],`

**Comment by Hasnayeen** [comment]
okay, then it should be `$data['assigned_to'] ?? null`

**Comment by djaca** [comment]
And notes, it forces to be string, but it should be optional...

**Pull request closed without merging**
