### PR TITLE
#663 Delete Direct Message

### PR DESCRIPTION
**Pull request by azisuazusa**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [ ] Check you have added tests that prove your fix is effective or that your feature works.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Add Feature #663 to delete direct message

💔Thank you!

### CODE REVIEW

**Comment by Hasnayeen** [comment]
this pr introduce new bugs and breaks deleting message in group message board, not acceptable

**Comment by azisuazusa** [comment]
I just knew there is a group message, will fix it.

**Comment by azisuazusa** [comment]
@Hasnayeen I just create the feature without breaking the group message, can you open this PR? Or should I create a new PR?

**Comment by Hasnayeen** [comment]
you can reopen the pr after fixing it

**Comment by azisuazusa** [comment]
I already push the code to the same branch

**Comment by Hasnayeen** [comment]
push your commit to this pr

**Pull request merged**
