### PR TITLE
[#188] Implemented notification for new group members

### PR DESCRIPTION
**Pull request by xkrupa12**
- Extended `MemberController::store()` to trigger notification on user
- Created `BecameNewMember` notification to send email to user with proper
message
- Extended `MemberTest` to test that notification has been send

### CODE REVIEW

**Comment by Hasnayeen** [comment]
Hey, so laravel notification will be used to send mail, but for frontend notification we're using spatie activitylog package so in the listener you need to log to it, hope it make sense :)

**Comment by xkrupa12** [comment]
Ok, I might misunderstood the task here - was this about sending user an email notification about them being added to a team or to create new notification that's displayed on front in upper right corner?
If later then I guess the whole solution is wrong and need to be redone.

**Comment by Hasnayeen** [comment]
Well it was about showing in page but you reminded we also need to send mail so its ok. But now problem is if we use laravel default notification for both mail and frontend, can we choose in certain situation where we need only frontend notification and not mail, can it be done with default notification?

**Comment by xkrupa12** [comment]
Take a look at this manual entry regarding Notifications - https://laravel.com/docs/5.7/notifications#specifying-delivery-channels

Based on that, you should be able to use single notification class to send notification via multiple channels - in this case I think you might be interested in mail and broadcast. I don't know whether you have or plan to implement frontend notifications via web sockets (using pusher or whatever else), but if you do, broadcast is the way how to do it. There's nice series about Laravel Echo - how it works and how to implement it relatively easily via pusher. I can look it up for you if you're interested.

Another option is to stay with event system - you can still define event and assign to it as many listeners as you want, so this solution might be reworked in a way that instead of calling `$user->notify()` you can simply dispatch event and set up listener for it to send email and another one to push frontend notification as well.

Let me know what's your opinion on this I don't mind extending/reworking the solution I developed here.

**Comment by Hasnayeen** [comment]
well that via delivery channel work by using user data but use case little different, for example I want to send mail & frontend notification when they are added but send only frontend notification when they are removed. that's why I'm not sure if default system will solve this problem

**Comment by xkrupa12** [comment]
I don't see a problem there, you'll just need to implement new notification like `RemovedFromMembers` that will have it's own setting of delivery channels to send notification through, in this case most likely only `broadcast`

**Comment by Hasnayeen** [comment]
Oh yes, you're right, misunderstood it completely.

**Comment by xkrupa12** [comment]
Ok so if we're settled on that, let's get back to this issue. What needs to be done in order to close it?

**Pull request merged**
