### PR TITLE
Update Farsi (Persian) translate

### PR DESCRIPTION
**Pull request by aznadesign**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [x] Check you have added tests that prove your fix is effective or that your feature works.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Please describe your pull request.

💔Thank you!

### CODE REVIEW

**Comment by Hasnayeen** [comment]
previous pr has already been merged, this is not necessary

**Comment by aznadesign** [comment]
@Hasnayeen I see you update en lang files today and updated them in fa files.
What is the problem?

**Comment by Hasnayeen** [comment]
the same pr has already been merged, https://github.com/iluminar/goodwork/pull/669
this is duplicate, please do not open duplicate pr

**Comment by aznadesign** [comment]
Check the changed files. I didn`t open duplicate PR.

**Comment by Hasnayeen** [comment]
I've checked both pr and both have same changes, compare yourself ([677](https://github.com/iluminar/goodwork/pull/677/files) and [669](https://github.com/iluminar/goodwork/pull/669/files)) if you're trying to complete hacktoberfest challenge use this repo please https://github.com/Dhroov7/Hacktoberfest2019 and send pr to that.

**Comment by aznadesign** [comment]
I think my last changes not committed. I work on hacktoberfest but I don`t like to complete that without effect on the FOSS. If you think my PR is duplicate, close that.

**Pull request closed without merging**
