### PR TITLE
[#173] Created API endpoint to store new comments

### PR DESCRIPTION
**Pull request by xkrupa12**
- Registered POST route /discussions/{discussion}/comments
- Implemented CommentController handling the request
- Implemented CommentRepository handling storing of new comment into DB
- Created new model for comment + defined relationships with related
models (User, Discussion)
- Created migration for comments - create_comments_table
- Implemented feature test for new endpoint and unit test for repository

### CODE REVIEW

**Comment by xkrupa12** [comment]
That code style checking is quite challenging

**Comment by Hasnayeen** [comment]
@xkrupa12 I think you're working in windows machine which use CRLF but git need LF. You can set up your editor to set up end of line sequence.

**Comment by xkrupa12** [comment]
I fact I'm using Debian & PHPStorm with LF

**Comment by Hasnayeen** [comment]
Ignore StyleCI error in future, It'll commit the fixes on dev after merging I think

**Comment by xkrupa12** [comment]
Fair enough, cheers!

**Pull request merged**
