### PR TITLE
Issue698 remove confirm password on registration #698

### PR DESCRIPTION
**Pull request by RageZBla**
### Make sure you've reviewed the checklist. (DO NOT REMOVE)
🚨Please review the [guidelines for contributing](https://github.com/iluminar/goodwork/wiki/Contribution-Guideline) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev branch**. Also you should start *your branch* off *dev branch*.
- [x] Check you have included issue number in your pr (e.g #23).
- [x] Check you have added tests that prove your fix is effective or that your feature works.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] Check you added any notable changes to the `CHANGELOG.md` file.

### Description
Remove password confirmation on registration page. See #698

💔Thank you!

### CODE REVIEW

**Comment by Hasnayeen** [comment]
@RageZBla confirm password check should be removed from backend as well

**Comment by RageZBla** [comment]
@Hasnayeen I tried to look around could not find the place it was implemented, would you mind showing us what part if affected?

**Comment by Hasnayeen** [comment]
check this [line](https://github.com/iluminar/goodwork/blob/7c9e05ea92e5a8111a9515422adc0c154633cd08/app/Core/Http/Controllers/Auth/RegisterController.php#L64)

**Comment by RageZBla** [comment]
@Hasnayeen thanks :+1:, updated the MR.

**Pull request merged**
